### PR TITLE
Fix the service name used by the ubbagent

### LINKED ISSUE #36: Ubbagent does not seem to be sending data
It seems like there is something wrong with the `ubbagent` container that runs inside the cert-manager controller pod in 1.1.0-gcm.3.

> Error 403: Permission 'servicemanagement.services.check' denied on service '<redacted_3rd_party_service>'

Full log:

```log
I0311 16:34:28.003237       1 servicecontrol.go:87] ServiceControlEndpoint:Send(): serviceName:  jetstack-secure-for-cert-manager.jetstack-public.appspot.com  body:  {"operations":[{"consumerId":"project:pr-2e981f0d7882bc90","endTime":"2021-03-11T16:34:28Z","metricValueSets":[{"metricName":"jetstack-secure-for-cert-manager.jetstack-public.appspot.com/time","metricValues":[{"endTime":"2021-03-11T16:34:28Z","int64Value":"60","startTime":"2021-03-11T16:33:28Z"}]}],"operationId":"423286a5-edaa-45de-80cb-69dca73814d3","operationName":"jetstack-secure-for-cert-manager.jetstack-public.appspot.com/report","startTime":"2021-03-11T16:33:28Z","userLabels":{"goog-ubb-agent-id":"10663b6a-7a4b-4015-abd4-a4f6e2fdc1e1"}}]}
E0311 16:34:28.016559       1 retry.go:216] RetryingSender.maybeSend [*googleapi.Error - will NOT retry]: googleapi: Error 403: Permission 'servicemanagement.services.check' denied on service '<redacted_3rd_party_service>'., forbidden
```

converted to YAML, the body is:

```yaml
operations:
  - consumerId: "project:pr-2e981f0d7882bc90"
    endTime: "2021-03-11T16:34:28Z"
    metricValueSets:
      - metricName: jetstack-secure-for-cert-manager.jetstack-public.appspot.com/time
        metricValues:
          - endTime: "2021-03-11T16:34:28Z"
            int64Value: "60"
            startTime: "2021-03-11T16:33:28Z"
    operationId: 423286a5-edaa-45de-80cb-69dca73814d3
    operationName: jetstack-secure-for-cert-manager.jetstack-public.appspot.com/report
    startTime: "2021-03-11T16:33:28Z"
    userLabels:
      goog-ubb-agent-id: 10663b6a-7a4b-4015-abd4-a4f6e2fdc1e1
```

It might be due to the fact that I did not know what to put in the Application `deploy-info` annotation. Currently, the annotation looks like this:

```yaml
apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  annotations:
    marketplace.cloud.google.com/deploy-info: '{"partner_id": "partner", "product_id": "jetstack-secure", "partner_name": "Jetstack"}'
```

### PR DESCRIPTION
**Pull request by maelvls**
Fixes #36

### CODE REVIEW

**Comment by maelvls** [comment]
I fixed the bug #36 that prevented ubbagent from heartbeating (= no way to bill customers). I released `1.1.0-gcm.4`. The plan is to have the app released on Monday 12 March 2021.

<details>
<summary>step by step process</summary>

first I built `1.1.0-gcm.3` deployer

```
% gcloud builds submit --project jetstack-public --timeout 1800s --config cloudbuild.yaml \
  --substitutions _CLUSTER_NAME=smoke-test,_CLUSTER_LOCATION=europe-west2-b,_APP_MINOR_VERSION=1.1,_APP_VERSION=1.1.0-gcm.3
```

- [logs](https://console.cloud.google.com/cloud-build/builds/f73c91b9-a1d0-4974-8536-8287c0f69d39?project=885059085598)
- image: gcr.io/jetstack-public/jetstack-secure-for-cert-manager/deployer:1.1.0-gcm.3

Finally, I did

```sh
git tag 1.1.0-gcm.4
```

And I went to the UI, updated the image and "Save" and Submit for review.

</details>

**Review by wallrj — APPROVED** [review]
/lgtm

**Comment by wallrj** [comment]
@maelvls I added a hold here too, in case it depended on  #35  being merged first.

**Pull request merged**
